const ActionsTitles = {
  ProductsActions: {
    // get products
    GET_PRODUCTS: "GET_PRODUCTS",
    GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
    GET_PRODUCTS_ERROR: "GET_PRODUCTS_ERROR",

    // search products
    SEARCH_PRODUCTS: "SEARCH_PRODUCTS",
    SEARCH_PRODUCTS_SUCCESS: "SEARCH_PRODUCTS_SUCCESS",
    SEARCH_PRODUCTS_ERROR: "SEARCH_PRODUCTS_ERROR",
  },
  CartActions: {
    // load cart
    LOAD_CART: "LOAD_CART",
    LOAD_CART_SUCCESS: "LOAD_CART_SUCCESS",
    LOAD_CART_ERROR: "LOAD_CART_ERROR",

    // add to cart
    ADD_TO_CART: "ADD_TO_CART",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_ERROR: "ADD_TO_CART_ERROR",

    // remove from cart
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    REMOVE_FROM_CART_SUCCESS: "REMOVE_FROM_CART_SUCCESS",
    REMOVE_FROM_CART_ERROR: "REMOVE_FROM_CART_ERROR",

    // clear cart
    CLEAR_CART: "CLEAR_CART",
    CLEAR_CART_SUCCESS: "CLEAR_CART_SUCCESS",
    CLEAR_CART_ERROR: "CLEAR_CART_ERROR",
  },
};

export default ActionsTitles;
