const ActionsTitles = {
  ProductsActions: {
    GET_PRODUCTS: "GET_PRODUCTS",
    GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
    GET_PRODUCTS_ERROR: "GET_PRODUCTS_ERROR",
  },
  CartActions: {
    LOAD_CART: "LOAD_CART",
    LOAD_CART_SUCCESS: "LOAD_CART_SUCCESS",
    LOAD_CART_ERROR: "LOAD_CART_ERROR",

    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    CLEAR_CART: "CLEAR_CART",
    UPDATE_CART: "UPDATE_CART",
  },
};

export default ActionsTitles;
